name: Tests

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Download dx
      run: curl -sSL http://dioxus.dev/install.sh | sh
    - name: Format
      run: cargo fmt
      run: dx fmt
      run: git diff --exit-code
    - name: Build
      run: dx bundle
    - name: Lint
      run: cargo clippy
